apiVersion: v1
kind: Namespace
metadata:
  name: nginx-serve-filter
  labels:
    istio-injection: "disabled"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-serve-filter
  namespace: nginx-serve-filter
spec:
  selector:
    matchLabels:
      app: nginx-serve-filter
  template:
    metadata:
      labels:
        app: nginx-serve-filter
    spec:
      containers:
      - name: nginx-serve-filter
        image: tomijange/nginx-serve-filter:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-serve-filter-service
  namespace: nginx-serve-filter
spec:
  type: ClusterIP
  selector:
    app: nginx-serve-filter
  ports:
  - port: 80
    targetPort: 80