[package]
name = "actix-wasm-filter"
version = "0.1.0"
edition = "2021"

[lib]
name = "actixenvoyfilter"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy-wasm = "0.1.0"
primes = "0.3.0"
log = "0.4"

