apiVersion: apps/v1
kind: Deployment
metadata:
  name: actix-collector-deployment
spec:
  selector:
    matchLabels:
      app: actix-collector
  template:
    metadata:
      labels:
        app: actix-collector
    spec:
      containers:
      - name: actix-collector
        image: jmgoyesc/actix-collector
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
